config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :livros
  resources :resenhas
  get 'sessions/new'
  get 'users/new'
  get '/buscar' => 'livros#buscar'
  post '/resultado' => 'livros#resultado'
  get 'my_ad'   => 'livros#ad'
  
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'
  
  scope '/resenhas' do
    resources :users do
      resources :livros
    end
  end
  
  resources :conversations do
    resources :messages
  end

end

app/models/resenha.rb
class Resenha < ActiveRecord::Base 
  belongs_to :idUser, :foreign_key => :idUser, class_name: 'User'
  belongs_to :idLivro, :foreign_key => :idLivro, class_name: 'Livro'

  validates_uniqueness_of :idUser, :scope => :idLivro

  scope :between, -> (idUser, idLivro) do
    where("(resenhas.idUser = ? AND resenhas.idLivro =?) OR (resenhas.idUser = ? AND resenhas.idLivro =?)", idUser, idLivro, idUser, idLivro)
  end
end

app/controllers/resenhas_controller.rb
class ResenhasController < ApplicationController
  before_action :set_resenha, only: [:show, :edit, :update, :destroy]

  # GET /resenhas
  # GET /resenhas.json
  def index
    @resenhas = Resenha.all
  end

  # GET /resenhas/1
  # GET /resenhas/1.json
  def show
  end

  # GET /resenhas/new
  def new
    @resenha = Resenha.new
  end

  # GET /resenhas/1/edit
  def edit
  end

  # POST /resenhas
  # POST /resenhas.json
  def create
    if Resenha.between(params[:idUser],params[:idLivro]).present?
      @resenha = Resenha.between(params[:idUser],params[:idLivro]).first
    else
      @resenha = Resenha.create!(resenha_params)
    end

    respond_to do |format|
      if @resenha.save
        format.html { redirect_to @resenha, notice: 'Resenha foi criada com sucesso!' }
        format.json { render :show, status: :created, location: @resenha }
      else
        format.html { render :new }
        format.json { render json: @resenha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resenhas/1
  # PATCH/PUT /resenhas/1.json
  def update
    respond_to do |format|
      if @resenha.update(resenha_params)
        format.html { redirect_to @resenha, notice: 'Resenha foi editada com sucesso.' }
        format.json { render :show, status: :ok, location: @resenha }
      else
        format.html { render :edit }
        format.json { render json: @resenha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resenhas/1
  # DELETE /resenhas/1.json
  def destroy
    @resenha.destroy
    respond_to do |format|
      format.html { redirect_to resenhas_url, notice: 'Resenha foi removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resenha
      @resenha = Resenha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resenha_params
      params.require(:resenha).permit(:idUser, :idLivro, :body, :data)
    end
end

app/helpers/resenhas_helper.rb
module ResenhasHelper
end

app/views/resenhas/_form.html.erb
<%= form_for(@resenha) do |f| %>
  <% if @resenha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resenha.errors.count, "error") %> prohibited this resenha from being saved:</h2>

      <ul>
      <% @resenha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :texto %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resenhas/edit.html.erb
<h1>Editing Resenha</h1>

<%= render 'form' %>

<%= link_to 'Show', @resenha %> |
<%= link_to 'Back', resenhas_path %>

app/views/resenhas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resenhas</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Livro</th>
      <th>Texto</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resenhas.each do |resenha| %>
      <tr>
        <td><%= resenha.user %></td>
        <td><%= resenha.livro %></td>
        <td><%= resenha.texto %></td>
        <td><%= resenha.data %></td>
        <td><%= link_to 'Show', resenha %></td>
        <td><%= link_to 'Edit', edit_resenha_path(resenha) %></td>
        <td><%= link_to 'Destroy', resenha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resenha', new_resenha_path %>

app/views/resenhas/new.html.erb
<h1>New Resenha</h1>

<%= render 'form' %>

<%= link_to 'Back', resenhas_path %>

app/views/resenhas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @resenha.user %>
</p>

<p>
  <strong>Livro:</strong>
  <%= @resenha.livro %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @resenha.texto %>
</p>

<p>
  <strong>Data:</strong>
  <%= @resenha.data %>
</p>

<%= link_to 'Edit', edit_resenha_path(@resenha) %> |
<%= link_to 'Back', resenhas_path %>