config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :livros
  resources :resenhas
  get 'sessions/new'
  get 'users/new'
  get '/buscar' => 'livros#buscar'
  post '/resultado' => 'livros#resultado'
  get 'my_ad'   => 'livros#ad'
  
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'
  
  scope '/resenhas' do
    resources :users do
      resources :livros
    end
  end
  
  resources :conversations do
    resources :messages
  end

end

app/models/livro.rb
class Livro < ActiveRecord::Base
    
    def self.search(query)
        where("nome LIKE :q", :q => "%#{query}%")
    end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:show, :edit, :update, :destroy]

  # GET /livros
  # GET /livros.json
  def index
    @livros = Livro.all
  end
  
  def ad
    @livros = Livro.all
  end

  def buscar
  end
  
  def resultado
    @livros = Livro.search(params[:query])
    respond_with @livros
  end
  
  # GET /livros/1
  # GET /livros/1.json
  def show
    @livro = Livro.find(params[:id])
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = Livro.new(livro_params)
      if @livro.save
        redirect_to @livro,
          :notice => "Cadastro de Livro Realizado com sucesso"
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro foi Atualizado com Sucesso!' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: 'Livro foi Apagado com Sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:nome, :autor, :publicacao, :isbn, :descricao, :valor, :owner, :idUser)
    end
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/livros/_form.html.erb
<%= form_for(@livro) do |f| %>
  <% if @livro.errors.any? %>
    <div id="error_explanation" style="border: none !important;">
      <h2><%= pluralize(@livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% @livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="border: none !important;">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field" style="border: none !important;">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field" style="border: none !important;">
    <%= f.label :publicacao %><br>
    <%= f.date_select :publicacao %>
  </div>
  <div class="field" style="border: none !important;">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field" style="border: none !important;">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field" style="border: none !important;">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <%= f.hidden_field :owner, :value => current_user.name %>
  <%= f.hidden_field :idUser, :value => current_user.id %>
  <div class="actions" style="border: none !important;">
    <%= f.submit "Anunciar"%>
  </div>
<% end %>

app/views/livros/ad.html.erb
<p id="notice"><%= notice %></p>

<h1>Meus anúncios</h1>
<% @livros.each do |livro| %>
<% end %>
<table border="1">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Autor</th>
      <th>Publicação</th>
      <th>ISBN</th>
      <th>Descrição</th>
      <th>Valor (R$) </th>
      <th colspan="3">Configuração</th>
    </tr>
  </thead>

  <tbody>
    <% @livros.each do |livro| %>
      <% if livro.owner.to_s.include? current_user.name %>
        <tr>
          <td><%= livro.nome %></td>
          <td><%= livro.autor %></td>
          <td><%= livro.publicacao %></td>
          <td><%= livro.isbn %></td>
          <td><%= livro.descricao %></td>
          <td><%= livro.valor %></td>
          <td><%= link_to 'Detalhes', livro %></td>
          <td><%= link_to 'Editar', edit_livro_path(livro) %></td>
          <td><%= link_to 'Apagar', livro, method: :delete, data: { confirm: 'Certeza que deseja fazer isso?' } %></td>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar Livro', new_livro_path %>

app/views/livros/buscar.html.erb
<%= form_tag resultado_path, :method => 'post' do %>
<%= text_field_tag :query, params[:query] %>
<%= submit_tag "Procurar Livro", :name => nil %>
<% end %>
<br/>
<%= link_to 'Voltar', livros_path %>

app/views/livros/edit.html.erb
<h1>Editing Livro</h1>

<%= render 'form' %>

<%= link_to 'Show', @livro %> |
<%= link_to 'Back', livros_path %>

app/views/livros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Livros</h1>

<table border="1">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Autor</th>
      <th>Publicação</th>
      <th>ISBN</th>
      <th>Descrição</th>
      <th>Valor (R$)</th>
      <th colspan="2">Contato</th>
    </tr>
  </thead>

  <tbody>
    <% @livros = Livro.order(:nome)
      @livros.each do |livro|%>
      <tr>
        <td><%= link_to livro.nome, "#{livro.id}/" %></td>
        <td><%= livro.autor %></td>
        <td><%= livro.publicacao %></td>
        <td><%= livro.isbn %></td>
        <td><%= livro.descricao %></td>
        <td><%= livro.valor %></td>
        <td><%= livro.owner %></td>
        <td>        
          <%= link_to 'Fale comigo!', conversations_path(sender_id: current_user.id, recipient_id: livro.idUser), method: 'post'%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Buscar Livro', buscar_path %>

app/views/livros/new.html.erb
<h1>Novo Livro</h1>

<%= render 'form' %>

<%= link_to 'Voltar', livros_path %>

app/views/livros/resultado.html.erb
<h3>Resultado da Busca</h3>
 <tbody>
     <% if @livros.nil? %>
     <tr>
      <td>O livro requisitado não foi encontrado no nosso banco de dados.</td>
      <td>Que tal tentar uma de nossas sugestões?</td>
     </tr>
     <% else @livros.each do |livro| #for enquanto tiver livros %>
         <tr>
             
             <td>Nome: <%=livro.nome%></td> </br></br>
             <td>ISBN: <%=livro.isbn%></td> </br></br>
             <td>Autor: <%=livro.autor%></td> </br></br>
             <td>Ano de Publicação: <%=livro.publicacao%></td> </br></br>
             <td>Descrição: <%=livro.descricao%></td></br></br>
         </tr>
         </br>
         <% end %>
 </tbody>
 <%= link_to 'Nova Busca', buscar_path %>
 <%= link_to 'Voltar', livros_path %>

app/views/livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @livro.nome %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>

<p>
  <strong>Publicação:</strong>
  <%= @livro.publicacao %>
</p>

<p>
  <strong>ISBN:</strong>
  <%= @livro.isbn %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @livro.descricao %>
</p>

<%= link_to 'Adicionar Resenha', new_user_livro_path(user_id: current_user.id, id: @livro.id) %>
<%= link_to 'Editar', edit_livro_path(@livro) %> |
<%= link_to 'Voltar', livros_path %>