config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :livros
  resources :resenhas
  get 'sessions/new'
  get 'users/new'
  get '/buscar' => 'livros#buscar'
  post '/resultado' => 'livros#resultado'
  get 'my_ad'   => 'livros#ad'
  
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'
  
  scope '/resenhas' do
    resources :users do
      resources :livros
    end
  end
  
  resources :conversations do
    resources :messages
  end

end

app/views/layouts/_footer.html.erb
<footer>
    <div class="footer">
    <p>Último Update em 10 de Novembro de 2016
    </p>
    <!-- fim do footer --></div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="logo">
    <center><img src="images/logo_clubedolivro.png" width="15%" alt="Clube do Livro"/></center>
    
  </div>
    <div class="header">
       <nav  class="menu_bar"> <!-- lista navegavel que forma a barra de menu -->
        <ul>
          <% if logged_in? %>
            <li><%= link_to "Home", current_user %></li>
            <li><%= link_to "Meu Anúncio", my_ad_path %></li>
            <li><%= link_to "Loja", Livro %></li>
            <li><%= link_to "Chat", Conversation %></li>
            <li><%= link_to "Usuários", users_path %></li>
            <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
            <li>
              <%= link_to "Sair", sign_out_path, method: "delete" %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Clubedolivro</title>
  	<link href="app/assets/stylesheets/oneColFixCtrHdr.css" rel="stylesheet" type="text/css">
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>

<style type="text/css">
body {
	font: 100%/1.4 Verdana, Arial, Helvetica, sans-serif;
	background-color: #CFAB53;
	margin: 0;
	padding: 0;
	color: #000;
}

.clear{
	clear:both;
}

.main{
	width:60%;
	display: inline;
	float: left;
	background-color: #DBC589;
	margin-left: 2px;
}

.sidebar1{
	background-color:#DBC589; 
	width:35%;
	display: inline;
	float: right;
	background-color: white;
	margin: 5px;
}

.sidebar1 ul li { 
	text-align: center;
}

.sidebar1 li{
	text-decoration:none;
}

#searchbar{
	display:block;
	float: right;
	margin-right: 10px;
}

.bookimage img{
	height:100 px;
	margin-left:auto;
	margin-right:auto;
	width: 150px;
}

.bookinfo p{
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 20px;
	padding:0 px;
	margin: 0px;
}

.form{
	border: 1px solid black;
	border-width: 70%;
}

.form input{
    width: 60%;
    height: 34px;    
    padding: 5px;
    box-sizing: border-box;
}

.form p{
	text-align:center;
}

/* ~~ Element/tag selectors ~~ */
ul, ol, dl { /* Due to variations between browsers, it's best practices to zero padding and margin on lists. For consistency, you can either specify the amounts you want here, or on the list items (LI, DT, DD) they contain. Remember that what you do here will cascade to the .nav list unless you write a more specific selector. */
	padding: 0;
	margin: 0;
}
h1, h2, h3, h4, h5, h6, p {
	margin-top: 0;	 /* removing the top margin gets around an issue where margins can escape from their containing div. The remaining bottom margin will hold it away from any elements that follow. */
	padding-right: 15px;
	padding-left: 15px; /* adding the padding to the sides of the elements within the divs, instead of the divs themselves, gets rid of any box model math. A nested div with side padding can also be used as an alternate method. */
}
a img { /* this selector removes the default blue border displayed in some browsers around an image when it is surrounded by a link */
	border: none;
}
/* ~~ Styling for your site's links must remain in this order - including the group of selectors that create the hover effect. ~~ */
a:link {
	text-decoration: none;

}
a:visited {
	text-decoration: none;
	color:white;

}
a:hover, a:active, a:focus { /* this group of selectors will give a keyboard navigator the same hover experience as the person using a mouse. */
	text-decoration: none;
}

/* ~~ this fixed width container surrounds the other divs ~~ */
.container {
	width: 960px;
	background-color: #FFF;
	margin: 0 auto; /* the auto value on the sides, coupled with the width, centers the layout */
}

/* ~~ the header is not given a width. It will extend the full width of your layout. It contains an image placeholder that should be replaced with your own linked logo ~~ */
.header {
	background-color: #DBC589;
}

/* ~~ This is the layout information. ~~ 

1) Padding is only placed on the top and/or bottom of the div. The elements within this div have padding on their sides. This saves you from any "box model math". Keep in mind, if you add any side padding or border to the div itself, it will be added to the width you define to create the *total* width. You may also choose to remove the padding on the element in the div and place a second div within it with no width and the padding necessary for your design.

*/

.content {

	padding: 20px 20px 20px 20px;
}

/* ~~ The footer ~~ */
.footer {
	padding: 10px 0;
	background-color: #DBC589;
	text-align: center;
}

.footer ul li {
	display: inline;
}
	



.footer li::after{content:" | ";}	

/* ~~ miscellaneous float/clear classes ~~ */
.fltrt {  /* this class can be used to float an element right in your page. The floated element must precede the element it should be next to on the page. */
	float: right;
	margin-left: 8px;
}
.fltlft { /* this class can be used to float an element left in your page. The floated element must precede the element it should be next to on the page. */
	float: left;
	margin-right: 8px;
}
.clearfloat { /* this class can be placed on a <br /> or empty div as the final element following the last floated div (within the #container) if the #footer is removed or taken out of the #container */
	clear:both;
	height:0;
	font-size: 1px;
	line-height: 0px;
}
ul li a {
	width: 100%;
	text-decoration: none;
	color: #FFFBFB;
	
}

.menu_bar li::after{content: " | ";}


ul li a:hover {
	color: #FFFFFF;
	background-color: #DBC589;
}

.menu_bar {
	text-align: left;
	background-color: #DBC589;
}

.account{
	display:inline;
	float:right;
}


.menu_bar li {
	display: inline;
	color: #FFFFFF;
}

.container .content h1 {
}
div {
	border: thin solid #000000;
}

}

</style>

<%= render 'layouts/header' %>
</head>
<body>
<div class="container">
<header>
  <div id="logo">
    <img src="images/logo_clubedolivro.png" width="15%" alt="Clube do Livro"/>
  </div>
    <div class="header">
       <nav  class="menu_bar"> <!-- lista navegavel que forma a barra de menu -->
        <ul>
          <% if logged_in? %>
            <li><%= link_to "Home", current_user %></li>
            <li><%= link_to "Meu Anúncio", my_ad_path %></li>
            <li><%= link_to "Loja", Livro %></li>
            <li><%= link_to "Chat", Conversation %></li>
            <li><%= link_to "Usuários", users_path %></li>
            <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
            <li><%= link_to "Sair", sign_out_path, method: "delete" %></li>
          
          <% end %>
        </ul>
      </nav>
    </div>
</header>
<div class="content"> <!-- aonde fica o conteudo do site -->
<%= yield %>
 <!-- fim do conteudo --></div>
<footer>
    <div class="footer">
    <p>Último Update em 24 de Novembro de 2016
    </p>
    <!-- fim do footer --></div>
</footer>
<!-- fim da div que agrupa header, conteudo e footer --></div>
</body>
</html>